If prices increase by 10% how do i update the value of 10k rows instantly

In [1]:
import numpy as np
prices = np.array([100,200,300,400])

prices * 1.10

array([110., 220., 330., 440.])

#Broadcasting(Uniformly increase the value of each val in array)

In [3]:
arr = np.array([[10,20,30],[40,50,60]])
arr + 5

array([[15, 25, 35],
       [45, 55, 65]])

# Slicing nad indexing

In [6]:
arr = np.array([10,20,30,40,50])
arr[2]
arr[1:4]

np.int64(30)

Q1) 

In [14]:
product_type = ["A","B","C"]
sales_day_1 = np.array([120,85,65])
sales_day_2 = np.array([150,90,75])
print("total sales per product",sales_day_1 + sales_day_2)


total sales per product [270 175 140]


In [10]:
sales_per = ((sales_day_2 - sales_day_1) / sales_day_1) * 100 
print("Change in percent % ",sales_per.round(2))

Change in percent %  [25.    5.88 15.38]


In [18]:
idx = sales_per.argmax() 
print("Product with highest growth ",product_type[idx])

Product with highest growth  A


Q2)


In [20]:
C = np.array([[25, 28, 30],
                  [22, 24, 26],
                  [30, 32, 33],
                  [27, 29, 31],
                  [20, 21, 23]])

In [21]:
F = C * (9/5) + 32
F

array([[77. , 82.4, 86. ],
       [71.6, 75.2, 78.8],
       [86. , 89.6, 91.4],
       [80.6, 84.2, 87.8],
       [68. , 69.8, 73.4]])

In [23]:
correction_data = [1,-1,0]
corrected_data = F + correction_data
corrected_data

array([[78. , 81.4, 86. ],
       [72.6, 74.2, 78.8],
       [87. , 88.6, 91.4],
       [81.6, 83.2, 87.8],
       [69. , 68.8, 73.4]])

Q3

In [37]:

bp = np.array([[120, 80],
               [135, 85],
               [140, 90],
               [110, 70],
               [125, 75]])
systolic = bp[:,0]
fixed = bp[systolic > 130]
fixed

array([[135,  85],
       [140,  90]])

In [40]:

diastolic = bp[:,1]
diastolic
bp[diastolic < 80] = 80
bp

array([[120,  80],
       [135,  85],
       [140,  90],
       [ 80,  80],
       [ 80,  80]])

Q4)

In [47]:
yields = np.array([[2.5, 3.0, 1.8],
                   [2.8, 3.2, 2.0],
                   [3.1, 2.9, 2.2],
                   [2.6, 3.1, 1.9]])
_ = [0.2,0.3,0.1]
yields + _
temp = yields

In [48]:

yields[:,-1] *= 1.1
yields

array([[2.5 , 3.  , 1.98],
       [2.8 , 3.2 , 2.2 ],
       [3.1 , 2.9 , 2.42],
       [2.6 , 3.1 , 2.09]])

In [49]:
average = yields.mean(axis = 0)
crop_type = ["A","B","C"]
idx = average.argmax()
crop_type[idx]

'B'

Q5)

In [50]:
scores = np.array([[85, 78, 92],
                   [88, 74, 90],
                   [70, 65, 80],
                   [95, 89, 96]])
type_of_stu = ["A","B","C"]
average_scores = scores.mean(axis = 0)
average_scores

array([84.5, 76.5, 89.5])

In [51]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix[1:,0 : 2]

array([[4, 5],
       [7, 8]])

In [52]:
#boolean indexing
arr = np.array([10,20,30,40])
arr > 23

array([False, False,  True,  True])

# Scenario: Farm Crop Yield Analysis
# A farm tracks the yield (in kilograms) of three different crops — Wheat, Rice, and Corn — across four seasons (Spring, Summer, Autumn, Winter).
# The farm manager wants to analyze the data to make better decisions for next year.
# Tasks
# - Create a 2D array representing crop yields for 3 crops across 4 seasons.
# - Rows = crops
# - Columns = seasons
# - Increase all yields by 10% to account for improved irrigation.
# - Extract only Wheat’s yields (the first crop).
# - Find the average yield per crop across all seasons.
# - Identify yields greater than 3000 kg (to see which crops/seasons performed exceptionally well).

In [62]:
crops = ["A","B","C"]
season = ["Summer","Winter","Autumn","Monsoon"]
farm = np.random.randint(100,size = (3,4))
farm

array([[63,  0, 21, 38],
       [96, 59, 35, 60],
       [13, 68, 57, 91]])

In [60]:
import pandas as pd
df = pd.DataFrame(farm,index = crops,columns = season)

In [63]:
df

Summer  Winter  Autmun  Monsoon
A      53      66      45       16
B      82      12      58       30
C      64      38      62       52

In [65]:
#increase by 10%
df = df * 1.1
df

Summer  Winter  Autmun  Monsoon
A  62.964  78.408  53.460   19.008
B  97.416  14.256  68.904   35.640
C  76.032  45.144  73.656   61.776

In [68]:
#extract only wheat
print(df.iloc[0,:])

Summer     62.964
Winter     78.408
Autmun     53.460
Monsoon    19.008
Name: A, dtype: float64


In [69]:
# the average yield per crop across all seasons
print(df.mean(axis = 1))

A    53.460
B    54.054
C    64.152
dtype: float64


In [70]:
#  yields greater than 3000 kg 
print(df.mean(axis = 1) > 3000)

A    False
B    False
C    False
dtype: bool


Task 2

In [73]:
import numpy as np
import pandas as pd

products = ["Gadgets", "Tools", "Machines"]
quarters = ["Q1", "Q2", "Q3", "Q4"]

df1 = pd.DataFrame(np.random.randint(4000,size=(3,4)) , index = products,columns = quarters)
df1

Q1    Q2    Q3    Q4
Gadgets   3217   985   849  3851
Tools      263  3460  2537   736
Machines  2815  1111   769    48

In [74]:
#increase by 5%
df_P = df1 * 1.05
df_P

Q1       Q2       Q3       Q4
Gadgets   3377.85  1034.25   891.45  4043.55
Tools      276.15  3633.00  2663.85   772.80
Machines  2955.75  1166.55   807.45    50.40

In [75]:
#average per product
print(df_P.mean(axis = 1))

Gadgets     2336.7750
Tools       1836.4500
Machines    1245.0375
dtype: float64


In [76]:
print(df_P[df_P > 500])

               Q1       Q2       Q3       Q4
Gadgets   3377.85  1034.25   891.45  4043.55
Tools         NaN  3633.00  2663.85   772.80
Machines  2955.75  1166.55   807.45      NaN


Pandas

In [77]:
data = { "Name" : ["A","B","C"],
        "Salary" : [50000,60000,64000]}
df_2 = pd.DataFrame(data)
df_2

Name  Salary
0    A   50000
1    B   60000
2    C   64000

In [78]:
type(df_2["Salary"])

pandas.core.series.Series

In [90]:
df = pd.read_csv("sample_data1 - Sheet1.csv")
df.head()

Employee_ID Department Region  Salary  Experience_Years  \
0         1001      Sales  North   45000                 2   
1         1002  Marketing  South   52000                 3   
2         1003      Sales   East   47000                 4   
3         1004         HR   West   40000                 1   
4         1005         IT  North   60000                 5   

   Performance_Rating  Monthly_Sales  
0                 4.0       120000.0  
1                 3.0        98000.0  
2                 5.0       150000.0  
3                 3.0            0.0  
4                 4.0            0.0

In [91]:
df.describe()

Employee_ID        Salary  Experience_Years  Performance_Rating  \
count    15.000000     15.000000         15.000000           14.000000   
mean   1008.000000  49666.666667          3.200000            3.785714   
std       4.472136   7158.079019          1.373213            0.892582   
min    1001.000000  39000.000000          1.000000            2.000000   
25%    1004.500000  45500.000000          2.000000            3.000000   
50%    1008.000000  49000.000000          3.000000            4.000000   
75%    1011.500000  52500.000000          4.000000            4.000000   
max    1015.000000  62000.000000          6.000000            5.000000   

       Monthly_Sales  
count      14.000000  
mean    76928.571429  
std     62039.025293  
min         0.000000  
25%         0.000000  
50%     95000.000000  
75%    128750.000000  
max    150000.000000

In [96]:
df.columns

Index(['Employee_ID', 'Department', 'Region', 'Salary', 'Experience_Years',
       'Performance_Rating', 'Monthly_Sales'],
      dtype='object')

In [97]:
df[df["Region"] == "North"]

Employee_ID Department Region  Salary  Experience_Years  \
0          1001      Sales  North   45000                 2   
4          1005         IT  North   60000                 5   
8          1009      Sales  North   46000                 3   
12         1013         IT  North   61000                 5   

    Performance_Rating  Monthly_Sales  
0                  4.0       120000.0  
4                  4.0            0.0  
8                  4.0       125000.0  
12                 4.0            NaN

In [99]:
# Sorting 
df.sort_values("Monthly_Sales",ascending = False)


Employee_ID Department Region  Salary  Experience_Years  \
2          1003      Sales   East   47000                 4   
10         1011      Sales   East   50000                 4   
13         1014      Sales  South   49000                 3   
5          1006      Sales  South   48000                 3   
8          1009      Sales  North   46000                 3   
0          1001      Sales  North   45000                 2   
1          1002  Marketing  South   52000                 3   
11         1012  Marketing   West   53000                 3   
6          1007  Marketing   East   51000                 2   
3          1004         HR   West   40000                 1   
4          1005         IT  North   60000                 5   
7          1008         IT   West   62000                 6   
9          1010         HR  South   39000                 2   
14         1015         HR   East   42000                 2   
12         1013         IT  North   61000                 5   

    Performance_Rating  Monthly_Sales  
2                  5.0       150000.0  
10                 5.0       140000.0  
13                 4.0       135000.0  
5                  4.0       130000.0  
8                  4.0       125000.0  
0                  4.0       120000.0  
1                  3.0        98000.0  
11                 NaN        92000.0  
6                  2.0        87000.0  
3                  3.0            0.0  
4                  4.0            0.0  
7                  5.0            0.0  
9                  3.0            0.0  
14                 3.0            0.0  
12                 4.0            NaN

In [100]:
# Grouping
df.groupby("Region")["Monthly_Sales"].sum()

Region
East     377000.0
North    245000.0
South    363000.0
West      92000.0
Name: Monthly_Sales, dtype: float64

In [101]:
df_3 = pd.read_csv("Dataset  - Sheet1.csv")
df_3.head()

Employee Department Quarter  Score
0     Amit      Sales      Q1     78
1    Priya         HR      Q1     85
2     John         IT      Q1     92
3     Sara    Finance      Q1     88
4    David      Sales      Q2     95

In [102]:
df_3[df_3["Department"] == "Sales"]

Employee Department Quarter  Score
0     Amit      Sales      Q1     78
4    David      Sales      Q2     95
8     Neha      Sales      Q3     99

In [ ]:
df.sort_values("

In [106]:
import pandas as pd
import numpy as np

customers = pd.read_csv("Customers1 - Sheet1.csv")
sales = pd.read_csv("Sales1 - Sheet1.csv")   
support = pd.read_csv("support1 - Sheet1.csv")


print("\nCustomers Info:")
print(customers.info())
print("\nSales Info:")
print(sales.info())
print("\nSupport Info:")
print(support.info())


customers["Age"].fillna(customers["Age"].median(), inplace=True)


customers.rename(columns={"CustomerID": "Cust_ID"}, inplace=True)
sales.rename(columns={"CustomerID": "Cust_ID"}, inplace=True)
support.rename(columns={"CustomerID": "Cust_ID"}, inplace=True)


sales["DiscountedPrice"] = sales["Price"] * 0.9


sales["Revenue"] = sales["Quantity"] * sales["Price"]


april_orders = sales[sales["OrderDate"].str.startswith("2023-04")]
print("\nApril Orders:\n", april_orders)


print("\nFirst 5 Sales Records:\n", sales.head())


north_customers = customers[customers["Region"] == "North"]


high_value_orders = sales[sales["Revenue"] > 50000]

print("\nNorth Customers:\n", north_customers)
print("\nHigh Value Orders:\n", high_value_orders)


sorted_customers = customers.sort_values(by="SignupDate")


sorted_sales = sales.sort_values(by="Revenue", ascending=False)

print("\nSorted Customers:\n", sorted_customers)
print("\nSorted Sales:\n", sorted_sales)


avg_revenue_product = sales.groupby("Product")["Revenue"].mean()


avg_resolution_issue = support.groupby("IssueType")["ResolutionTime"].mean()

print("\nAverage Revenue per Product:\n", avg_revenue_product)
print("\nAverage Resolution Time per Issue Type:\n", avg_resolution_issue)


merged_data = sales.merge(customers, on="Cust_ID").merge(support, on="Cust_ID")

print("\nMerged Dataset:\n", merged_data.head())


clv = sales.groupby("Cust_ID")["Revenue"].sum().reset_index()
clv.rename(columns={"Revenue": "CustomerLifetimeValue"}, inplace=True)


customers = customers.merge(clv, on="Cust_ID", how="left")

print("\nCustomers with CLV:\n", customers)


merged_data.to_csv("Cleaned_Data.csv", index=False)
print("\nCleaned dataset exported to Cleaned_Data.csv")



Customers Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   CustomerID  8 non-null      object 
 1   Name        8 non-null      object 
 2   Age         7 non-null      float64
 3   Region      8 non-null      object 
 4   SignupDate  8 non-null      object 
dtypes: float64(1), object(4)
memory usage: 452.0+ bytes
None

Sales Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   OrderID     8 non-null      object
 1   CustomerID  8 non-null      object
 2   Product     8 non-null      object
 3   Quantity    8 non-null      int64 
 4   Price       8 non-null      int64 
 5   OrderDate   8 non-null      object
dtypes: int64(2), object(4)
memory usage: 516.0+ bytes
None

Support Info:
<class 'pandas.core.frame.

/var/folders/v_/586nqpj536s2d596mm_4jw0c0000gn/T/ipykernel_6435/3045384187.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers["Age"].fillna(customers["Age"].median(), inplace=True)
